name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - apko
          - arc
          - archivist
          - bats
          - borgo
          - checksum
          - gh
          - go
          - golangci-lint
          - helm
          - helm-docs
          - kafka
          - kustomize
          - openapi-changes
          - openssh-server
          - postgres
          - psql
          - python
          - quarto
          - registry
          - registry-config
          - slsa-verifier
          - spectral
          - ssh-keygen
          - stainless
          - trivy
          - xcaddy
          - xk6

    steps:
      - uses: dkershner6/switch-case-action@v1
        id: constructor-args
        with:
          default: ""
          conditionals-with-values: |
            ${{ matrix.module == 'gh' }} => --github-token env:GITHUB_TOKEN

      - name: Run pipeline
        uses: dagger/dagger-for-github@e49f5bfe7f9a3593f38b9d7391f110d6dff48f94 # v6.8.0
        with:
          verb: call
          module: github.com/${{ github.repository }}/${{ matrix.module }}/tests@${{ github.ref }}
          args: ${{ steps.constructor-args.outputs.value }} all
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.13.1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  examples:
    name: Examples
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - helm
          - svix
          - trivy

    steps:
      - uses: dkershner6/switch-case-action@v1
        id: constructor-args
        with:
          default: ""
          conditionals-with-values: |
            ${{ matrix.module == 'gh' }} => --github-token env:GITHUB_TOKEN

      - name: Run pipeline
        uses: dagger/dagger-for-github@e49f5bfe7f9a3593f38b9d7391f110d6dff48f94 # v6.8.0
        with:
          verb: call
          module: github.com/${{ github.repository }}/${{ matrix.module }}/examples/go@${{ github.ref }}
          args: ${{ steps.constructor-args.outputs.value }} all
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.13.1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
