name: Publish

on:
  push:
    branches: [main]
    tags: ["**/v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - apko
          - arc
          - archivist
          - bats
          - borgo
          - checksum
          - gh
          - go
          - golangci-lint
          - helm
          - helm-docs
          - kafka
          - kustomize
          - openssh-server
          - psql
          - python
          - quarto
          - registry-config
          - slsa-verifier
          - spectral
          - ssh-keygen
          - stainless
          - xcaddy
          - xk6

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Set up magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@b46e247b898aa56e6d2d2e728dc6df6c84fdb738 # v7

      - name: Prepare Nix shell
        run: nix develop --impure .#ci

      - name: Publish
        run: nix develop --impure .#ci -c dagger publish
        env:
          DAGGER_MODULE: ${{ matrix.module }}
